# Generated by Django 3.1.5 on 2021-02-16 13:21

import ckeditor.fields
from django.db import migrations, models
import proyectos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=200, verbose_name='Título')),
                ('descripción', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to=proyectos.models.remplazarImagen, verbose_name='Imagen')),
                ('imagenDeFondo', models.ImageField(upload_to=proyectos.models.remplazarImagenDeFondo, verbose_name='Imagen de Fondo')),
                ('información', ckeditor.fields.RichTextField(default='', verbose_name='Informacion del proyecto')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-creado'],
            },
        ),
    ]
